export const mockProducts = [
    {
        id: 1,
        name: "Apple iPhone 15 Pro",
        category: "Smartphones",
        brand: "Apple",
        price: 1200,
    },
    {
        id: 2,
        name: "Samsung Galaxy S24",
        category: "Smartphones",
        brand: "Samsung",
        price: 900,
    },
    {
        id: 3,
        name: "Sony WH-1000XM5",
        category: "Headphones",
        brand: "Sony",
        price: 380,
    },
    {
        id: 4,
        name: "Dell XPS 13",
        category: "Laptops",
        brand: "Dell",
        price: 1350,
    },
    {
        id: 5,
        name: "Asus Vivobook 14",
        category: "Laptops",
        brand: "Asus",
        price: 700,
    },
    {
        id: 6,
        name: "Apple AirPods Pro",
        category: "Headphones",
        brand: "Apple",
        price: 250,
    },
    {
        id: 7,
        name: "HP Pavilion 15",
        category: "Laptops",
        brand: "HP",
        price: 850,
    },
    {
        id: 8,
        name: "Samsung Galaxy Buds 2",
        category: "Headphones",
        brand: "Samsung",
        price: 110,
    },
    {
        id: 9,
        name: "Sony Xperia 5",
        category: "Smartphones",
        brand: "Sony",
        price: 950,
    },
    {
        id: 10,
        name: "Apple MacBook Pro",
        category: "Laptops",
        brand: "Apple",
        price: 2000,
    },
];